import 'file_category.dart';

class SupportedFormats {
  static const Map<String, FileCategory> _extensionMap = {
    // Documents
    '.pdf': FileCategory.pdf,
    '.doc': FileCategory.document,
    '.docx': FileCategory.document,
    '.docm': FileCategory.document,
    '.dot': FileCategory.document,
    '.dotm': FileCategory.document,
    '.dotx': FileCategory.document,
    '.rtf': FileCategory.document,
    '.odt': FileCategory.document,
    '.pages': FileCategory.document,
    '.ppt': FileCategory.document,
    '.pptx': FileCategory.document,
    '.pptm': FileCategory.document,
    '.pot': FileCategory.document,
    '.potm': FileCategory.document,
    '.potx': FileCategory.document,
    '.pps': FileCategory.document,
    '.ppsx': FileCategory.document,
    '.ppsm': FileCategory.document,
    '.xls': FileCategory.document,
    '.xlsx': FileCategory.document,
    '.xlsm': FileCategory.document,
    '.xlt': FileCategory.document,
    '.xltm': FileCategory.document,
    '.xltx': FileCategory.document,
    '.csv': FileCategory.document,
    '.tsv': FileCategory.document,
    '.psv': FileCategory.document,
    '.ssv': FileCategory.document,
    '.xps': FileCategory.document,
    '.oxps': FileCategory.document,
    '.txt': FileCategory.text,
    '.log': FileCategory.text,
    '.conf': FileCategory.text,
    '.cfg': FileCategory.text,
    '.html': FileCategory.text,
    '.htm': FileCategory.text,
    '.xhtml': FileCategory.text,
    '.xml': FileCategory.text,
    '.md': FileCategory.text,

    // Images
    '.jpg': FileCategory.image,
    '.jpeg': FileCategory.image,
    '.png': FileCategory.image,
    '.gif': FileCategory.image,
    '.webp': FileCategory.image,
    '.bmp': FileCategory.image,
    '.svg': FileCategory.image,
    '.tiff': FileCategory.image,
    '.tif': FileCategory.image,
    '.psd': FileCategory.image,
    '.heic': FileCategory.image,
    '.heif': FileCategory.image,
    '.avif': FileCategory.image,
    '.avifs': FileCategory.image,
    '.ico': FileCategory.image,
    '.tga': FileCategory.image,
    '.targa': FileCategory.image,
    '.dds': FileCategory.image,
    '.exr': FileCategory.image,
    '.jp2': FileCategory.image,
    '.pbm': FileCategory.image,
    '.pgm': FileCategory.image,
    '.ppm': FileCategory.image,
    '.xbm': FileCategory.image,
    '.xpm': FileCategory.image,
    '.wbmp': FileCategory.image,
    '.sgi': FileCategory.image,
    '.ras': FileCategory.image,
    '.pfm': FileCategory.image,
    '.pcx': FileCategory.image,
    '.jng': FileCategory.image,
    '.mng': FileCategory.image,
    '.apng': FileCategory.image,
    '.pcd': FileCategory.image,
    '.fits': FileCategory.image,
    '.vtf': FileCategory.image,
    '.dib': FileCategory.image,
    '.thm': FileCategory.image,

    // Camera RAW
    '.arw': FileCategory.image,
    '.cr2': FileCategory.image,
    '.cr3': FileCategory.image,
    '.nef': FileCategory.image,
    '.nrw': FileCategory.image,
    '.dng': FileCategory.image,
    '.raf': FileCategory.image,
    '.rw2': FileCategory.image,
    '.orf': FileCategory.image,
    '.pef': FileCategory.image,
    '.srw': FileCategory.image,
    '.rwl': FileCategory.image,
    '.sr2': FileCategory.image,
    '.srf': FileCategory.image,
    '.mrw': FileCategory.image,
    '.mos': FileCategory.image,
    '.erf': FileCategory.image,
    '.kdc': FileCategory.image,
    '.dcr': FileCategory.image,
    '.bay': FileCategory.image,
    '.3fr': FileCategory.image,
    '.x3f': FileCategory.image,

    // Videos
    '.mp4': FileCategory.video,
    '.mkv': FileCategory.video,
    '.webm': FileCategory.video,
    '.3gp': FileCategory.video,
    '.mov': FileCategory.video,
    '.avi': FileCategory.video,
    '.wmv': FileCategory.video,
    '.flv': FileCategory.video,
    '.m4p': FileCategory.video,
    '.mpg': FileCategory.video,
    '.mpeg': FileCategory.video,
    '.m2ts': FileCategory.video,
    '.mts': FileCategory.video,
    '.vob': FileCategory.video,
    '.ogv': FileCategory.video,
    '.rm': FileCategory.video,
    '.rmvb': FileCategory.video,
    '.divx': FileCategory.video,
    '.mxf': FileCategory.video,
    '.dv': FileCategory.video,
    '.amv': FileCategory.video,
    '.nsv': FileCategory.video,
    '.yuv': FileCategory.video,
    '.swf': FileCategory.video,
    '.roq': FileCategory.video,
    '.bik': FileCategory.video,
    '.bk2': FileCategory.video,
    '.fli': FileCategory.video,
    '.flc': FileCategory.video,
    '.wtv': FileCategory.video,

    // Audio
    '.mp3': FileCategory.audio,
    '.aac': FileCategory.audio,
    '.m4a': FileCategory.audio,
    '.flac': FileCategory.audio,
    '.ogg': FileCategory.audio,
    '.oga': FileCategory.audio,
    '.opus': FileCategory.audio,
    '.wav': FileCategory.audio,
    '.mka': FileCategory.audio,
    '.3ga': FileCategory.audio,
    '.3gpa': FileCategory.audio,
    '.amr': FileCategory.audio,
    '.awb': FileCategory.audio,
    '.spx': FileCategory.audio,
    '.gsm': FileCategory.audio,
    '.dsf': FileCategory.audio,
    '.dff': FileCategory.audio,
    '.aa': FileCategory.audio,
    '.aax': FileCategory.audio,
    '.sf2': FileCategory.audio,
    '.sfz': FileCategory.audio,
    '.caf': FileCategory.audio,
    '.imy': FileCategory.audio,
    '.gp5': FileCategory.audio,
    '.gpx': FileCategory.audio,

    // Archives
    '.zip': FileCategory.archive,
    '.7z': FileCategory.archive,
    '.tar': FileCategory.archive,
    '.gz': FileCategory.archive,
    '.gzip': FileCategory.archive,
    '.tgz': FileCategory.archive,
    '.tar.gz': FileCategory.archive,
    '.bz2': FileCategory.archive,
    '.bzip2': FileCategory.archive,
    '.tbz': FileCategory.archive,
    '.tbz2': FileCategory.archive,
    '.tar.bz2': FileCategory.archive,
    '.jar': FileCategory.archive,
    '.cbz': FileCategory.archive,
    '.z': FileCategory.archive,
    '.rar': FileCategory.archive,
    '.iso': FileCategory.archive,
    '.ace': FileCategory.archive,
    '.arj': FileCategory.archive,
    '.lha': FileCategory.archive,
    '.lzh': FileCategory.archive,
    '.sit': FileCategory.archive,
    '.sitx': FileCategory.archive,
    '.cbr': FileCategory.archive,
    '.cb7': FileCategory.archive,
    '.cpio': FileCategory.archive,
    '.alz': FileCategory.archive,
    '.egg': FileCategory.archive,
    '.whl': FileCategory.archive,
    '.nupkg': FileCategory.archive,
    '.gem': FileCategory.archive,
    '.par2': FileCategory.archive,

    // APK
    '.apk': FileCategory.apk,

    // Code
    '.py': FileCategory.code,
    '.js': FileCategory.code,
    '.mjs': FileCategory.code,
    '.cjs': FileCategory.code,
    '.ts': FileCategory.code,
    '.tsx': FileCategory.code,
    '.jsx': FileCategory.code,
    '.java': FileCategory.code,
    '.kt': FileCategory.code,
    '.kts': FileCategory.code,
    '.swift': FileCategory.code,
    '.dart': FileCategory.code,
    '.c': FileCategory.code,
    '.cpp': FileCategory.code,
    '.cxx': FileCategory.code,
    '.cc': FileCategory.code,
    '.h': FileCategory.code,
    '.hpp': FileCategory.code,
    '.hxx': FileCategory.code,
    '.cs': FileCategory.code,
    '.vb': FileCategory.code,
    '.fs': FileCategory.code,
    '.fsx': FileCategory.code,
    '.go': FileCategory.code,
    '.rs': FileCategory.code,
    '.php': FileCategory.code,
    '.rb': FileCategory.code,
    '.rbp': FileCategory.code,
    '.pl': FileCategory.code,
    '.pm': FileCategory.code,
    '.r': FileCategory.code,
    '.rmd': FileCategory.code,
    '.lua': FileCategory.code,
    '.scala': FileCategory.code,
    '.clj': FileCategory.code,
    '.cljs': FileCategory.code,
    '.hs': FileCategory.code,
    '.lhs': FileCategory.code,
    '.elm': FileCategory.code,
    '.ex': FileCategory.code,
    '.exs': FileCategory.code,
    '.erl': FileCategory.code,
    '.hrl': FileCategory.code,
    '.ml': FileCategory.code,
    '.mli': FileCategory.code,
    '.nim': FileCategory.code,
    '.zig': FileCategory.code,
    '.d': FileCategory.code,
    '.pas': FileCategory.code,
    '.pp': FileCategory.code,
    '.ada': FileCategory.code,
    '.adb': FileCategory.code,
    '.ads': FileCategory.code,
    '.f': FileCategory.code,
    '.f90': FileCategory.code,
    '.for': FileCategory.code,
    '.cob': FileCategory.code,
    '.cbl': FileCategory.code,
    '.groovy': FileCategory.code,
    '.gradle': FileCategory.code,
    '.asm': FileCategory.code,
    '.s': FileCategory.code,
    '.tcl': FileCategory.code,
    '.m': FileCategory.code,
    '.mlx': FileCategory.code,
    '.jl': FileCategory.code,
    '.coffee': FileCategory.code,
    '.cr': FileCategory.code,
    '.ahk': FileCategory.code,
    '.gd': FileCategory.code,
    '.wasm': FileCategory.code,
    '.wat': FileCategory.code,
    '.tf': FileCategory.code,
    '.hcl': FileCategory.code,
    '.bicep': FileCategory.code,
    '.proto': FileCategory.code,
    '.graphql': FileCategory.code,
    '.gql': FileCategory.code,
    '.sol': FileCategory.code,
    '.awk': FileCategory.code,
    '.dockerfile': FileCategory.code,
    '.sh': FileCategory.code,
    '.bash': FileCategory.code,
    '.zsh': FileCategory.code,
    '.ps1': FileCategory.code,
    '.psm1': FileCategory.code,
    '.bat': FileCategory.code,
    '.cmd': FileCategory.code,
    '.sql': FileCategory.code,

    // eBooks
    '.epub': FileCategory.ebook,
    '.mobi': FileCategory.ebook,
    '.azw': FileCategory.ebook,
    '.azw3': FileCategory.ebook,
    '.kfx': FileCategory.ebook,
    '.pdb': FileCategory.ebook,
    '.prc': FileCategory.ebook,
    '.lit': FileCategory.ebook,
    '.lrf': FileCategory.ebook,
    '.lrx': FileCategory.ebook,
    '.fb2': FileCategory.ebook,
    '.fb3': FileCategory.ebook,

    // Email
    '.eml': FileCategory.email,
    '.emlx': FileCategory.email,
    '.msg': FileCategory.email,
    '.oft': FileCategory.email,
    '.pst': FileCategory.email,
    '.ost': FileCategory.email,
    '.mbox': FileCategory.email,
    '.mbx': FileCategory.email,
    '.dat': FileCategory.email,
    '.vcf': FileCategory.email,
    '.ics': FileCategory.email,
    '.ical': FileCategory.email,
  };

  static FileCategory? getCategoryFromExtension(String extension) {
    return _extensionMap[extension.toLowerCase()];
  }

  static FileCategory getCategoryFromFileName(String fileName) {
    final extension = fileName.contains('.')
        ? fileName.substring(fileName.lastIndexOf('.'))
        : '';
    return getCategoryFromExtension(extension) ?? FileCategory.unknown;
  }

  static bool isSupported(String fileName) {
    final extension = fileName.contains('.')
        ? fileName.substring(fileName.lastIndexOf('.'))
        : '';
    return _extensionMap.containsKey(extension.toLowerCase());
  }

  static List<String> getExtensionsForCategory(FileCategory category) {
    return _extensionMap.entries
        .where((entry) => entry.value == category)
        .map((entry) => entry.key)
        .toList();
  }

  static List<FileCategory> getAllCategories() {
    return FileCategory.values;
  }
}
